---
title: "Comparison MH - Bootstrap"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

This script shows not only the Bootstrap Comparison and but also 
the conjugation estimate as the function will tell

```{r,echo=TRUE,eval=T}

Data <- read.csv(file = "Data.csv", header = TRUE, sep = ",", dec = ".")


n.states <- c("Schleswig-Holstein", "Hamburg","Niedersachsen","Bremen",
              "NRW","Hessen","Rheinland-Pfalz","Baden-Württemberg","Bayern","Saarland",
              "Berlin","Brandenburg","M-Vorpommern","Sachsen","Sachsen-Anhalt","Thüringen")

n.age <- c("A00-A04", "A05-A14", "A15-A34", "A35-A59", "A60-A79", "A80+")
gender <- c("M", "W", "unbekannt")

Data$Refdatum = as.Date(Data$Ref, format = "%Y-%m-%d")
```

```{r,echo=TRUE,eval=T}
estimation <- function(data = Data, Bundeslaender = TRUE, Bundesland_Klasse, 
                       Landkreise = FALSE,Landkreis_Klasse,
                       Geschlechts_Klasse, Alter_Klasse, alpha_0, beta_0,
                       MH_algorithm = TRUE, Bayes_Estimate = TRUE, 
                       n.sims = 1000, time.stamp, Zeitpunkt, Bootstrap = TRUE,
                       bootstrap.sim = 1000){
  
  #####set prior distribution
  
  expected_prior <- alpha_0/(alpha_0 + beta_0)
  
  ##prior is set as defined distribution which will be drawn from random
  
  if(Bundeslaender){
    frame <- data[(data$Bundesland == Bundesland_Klasse),]
  }
  if(Landkreise){
    frame <- data[(data$IdLandkreis == Landkreis_Klasse),]
  }
  frame <- frame[(frame$Geschlecht == Geschlechts_Klasse),]
  
  frame <- frame[(frame$Altersgruppe == Alter_Klasse),]

  frame <- frame[,c(5,10,11)]
  
  time_frame <- as.Date(frame[,1])  
  if(time.stamp){
    zeitpunkt_ende <- rev(time_frame)[1]
    zeitpunkt_neu = as.Date(Zeitpunkt)
    pos <- rev(which(time_frame %in% as.Date(zeitpunkt_ende, 
                                                 format = "%Y-%m-%d")))[1]
    if(zeitpunkt_ende < zeitpunkt_neu){
      frame <- frame[1:pos ,]
    }
    else{
      while(sum(frame$Refdatum == Zeitpunkt, na.rm = T) == 0){
        zeitpunkt_neu <- zeitpunkt_neu +1
        zeitpunkt_neu <- as.Date(zeitpunkt_neu)
     }
    end_date <- rev(which(time_frame %in% zeitpunkt_neu))[1]
    frame <- frame[1:end_date ,]
    }
  }
  else{
    zeitpunkt_ende <- rev(time_frame)[1]
    pos <- rev(which(time_frame %in% as.Date(zeitpunkt_ende, 
                                                 format = "%Y-%m-%d")))[1]
    frame <- frame[1:pos ,]
  }
  
  specific_data <- apply(frame[,2:3], 2, sum)
  ratio <- specific_data[2]/specific_data[1]
  
  ##build the data respective binomial distribution
  
  data_distribution <- c(rep(0, specific_data[1]), rep(1, specific_data[2]))

  ##### Bayes estimation -- no MH
  
  if(Bayes_Estimate){
    alpha_bayes <- specific_data[2] + alpha_0
    beta_bayes <- specific_data[1] - specific_data[2] + beta_0
    bayes_estimate <- alpha_bayes/(alpha_bayes + beta_bayes)
  }

  ####MCMC MH 
  theta_vec <- NULL
    
  if(MH_algorithm){
  
    theta_0 <- rbeta(n = 1, shape1 = alpha_0, shape2 = beta_0)
    theta_vec <- rep(0, n.sims+1) #create posterior vector
    theta_vec[1] <- theta_0 #initialize posterior vector
    
    for (t in 1:n.sims){
      
      theta_star <- rbeta(n = 1, shape1 = alpha_0, shape2 = beta_0) #proposal from prior    
      theta_t <- theta_vec[t] #previous accepted value for posterior  
      
      #Create MH-Ratio using log-likelihoods
      
      MH_Ratio <- sum(log(dbinom(data_distribution, size = 1, log = F, prob = theta_t)))/
        sum(log(dbinom(data_distribution, size = 1, log = F, prob = theta_star)))
     
       
      #sample with MH ratio
      
      mh_prob <- c(min(1,MH_Ratio), 1-min(1,MH_Ratio))
      
      theta_vec[t+1] <- sample(x = c(theta_star, theta_t),size = 1,prob = mh_prob)              
    }  
    mh_estimate <- mean(theta_vec)
    quantiles <- quantile(theta_vec, probs = c(0.1,0.9))
    h <- hist(theta_vec[(0.3*n.sims):n.sims], plot = F)
    cols <- c(0, 4, 0)
    k<- cols[findInterval(h$mids, quantile(theta_vec, probs = c(0.1,0.9)),
                          rightmost.closed=T, all.inside=F)+1]
    if(Bootstrap == F){
    par(mfrow = c(2,2))
    plot(h, col = k, main = paste("Histogram of posterior vector", Bundesland_Klasse), 
         xlab = "Values of Theta Vector")
    
    
    plot(dbeta(seq(0,0.2,le=1000), shape1 = alpha_bayes, shape2 = beta_bayes), 
         type = "l", ylab = "Probability", main = "Posterior Distribution")
    plot(x = 1:4, y = c(ratio, bayes_estimate, mh_estimate, expected_prior),
         col = 1:4, pch = 16, ylim = c(0,expected_prior + 0.01), xlim = c(0,5),
         ylab = "Probability", main = "Comparison between estimates")
    text(x = 1:4,
         y = c(ratio,bayes_estimate, mh_estimate,
               expected_prior)+0.006,c("ratio","bayes_estimate","mh_estimate", 
                                       "expected_prior"), cex = .7)
    plot(theta_vec[(0.3*n.sims):n.sims], type = "l", ylab = "Mixing",
         main = "Mixing of posterior values")
    
    
  return(list(Bayes_Estimate = bayes_estimate, MH_Estimate = mean(theta_vec),
              ratio = ratio, infection_data = specific_data,
              expected_prior = expected_prior))
    }
  }
  if(Bootstrap){
    
    B <- bootstrap.sim
    estimates <- NULL
    n.bootstrap <- length(data_distribution)
    
    for(b in 1:B){
      new_sample_data <- sample(data_distribution, size = n.bootstrap,
                                replace = TRUE)
      estimates[b] <- mean(new_sample_data)
    }
   
    h2 <- hist(estimates, plot = F) 
  
  
  par(mfrow = c(1,2))
    plot(h, col = k, main = paste("Histogram of posterior vector", Bundesland_Klasse), 
        xlab = "Values of Theta Vector")
    plot(h2, main = "Bootstrap distribution" )
  
  return(list(MH_Estimate = mean(theta_vec), quantiles = quantiles, ratio = ratio))
  }
}

```

Showing credible intervals and comparisons

```{r,echo=TRUE,eval=T}


estimation(Bundeslaender = T, Bundesland_Klasse = "Rheinland-Pfalz",
           Geschlechts_Klasse = "M", Alter_Klasse = "A35-A59", alpha_0 = 4, 
           beta_0 = 20, Zeitpunkt = "2020-10-27", Bootstrap = F, time.stamp = T,
           MH_algorithm = T, Bayes_Estimate = T)

```





```{r,echo=TRUE,eval=TRUE}

estimation(Bundeslaender = T, Bundesland_Klasse = "Rheinland-Pfalz",
           Geschlechts_Klasse = "M", Alter_Klasse = "A35-A59", alpha_0 = 4, 
           beta_0 = 20, Zeitpunkt = "2020-10-27", Bootstrap = T, time.stamp = T)


```
